server:
  port: 8103

spring:
  profiles:
    include: druid,common



#设置静态资源路径，多个以逗号分隔
  resources:
    static-locations: classpath:/static/echart/*,classpath:/static/layui/*,classpath:/static/platform/*，classpath:/static/platform/*
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


