spring:
  redis:
    database: 0
    host: 59.110.160.100
    port: 6379
    password: okmngtcxqsdr628j8gf58hhf9kl09mj78hbkk6fjk0pk
    timeout: 3600 #超时时间
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接 默认8
        max-wait: -1  #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接

